#	P H A N T O M

/gate/world/daughters/name phantom_cylinder
/gate/world/daughters/insert cylinder
/gate/phantom_cylinder/setMaterial Water
/gate/phantom_cylinder/vis/setColor grey
/gate/phantom_cylinder/geometry/setRmax   10. cm
/gate/phantom_cylinder/geometry/setHeight 20.0 cm
/gate/phantom_cylinder/placement/setTranslation   0. 0. 0. cm


/gate/phantom_cylinder/attachPhantomSD
/gate/phantom_cylinder/vis/forceSolid
